# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 19:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_commit', models.IntegerField(default=0)),
                ('room_visit', models.IntegerField(default=0)),
                ('event_visit', models.IntegerField(default=0)),
                ('contribution', models.IntegerField(default=0)),
                ('login_counter', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
