# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Osori_rpg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
