# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Osori_rpg', '0003_exprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exprequest',
            name='options',
            field=models.CharField(choices=[('Room_Visit', 'Room_Visit'), ('Event_Visit', 'Event_Visit'), ('Contribution', 'Contribution')], max_length=100),
        ),
    ]
